In [1]:
# How to generate an array with random values
import numpy as np
a = np.random.random((10,4))
print(a)

[[0.74136147 0.72813536 0.03935882 0.05685399]
 [0.55683738 0.09298074 0.04876567 0.05611838]
 [0.33485263 0.95761548 0.70433113 0.66648884]
 [0.8138952  0.36006705 0.00309397 0.50905702]
 [0.95095022 0.62157033 0.03826442 0.61274149]
 [0.5985246  0.1256595  0.0664599  0.65486276]
 [0.23555828 0.42642508 0.75105377 0.69864967]
 [0.11085185 0.96650777 0.20005389 0.12000008]
 [0.7390861  0.35096408 0.45338379 0.83371174]
 [0.97180895 0.24144401 0.95681484 0.38220045]]


In [2]:
print(a.shape)
print(a.size)

(10, 4)
40


In [3]:
# How to generate 5 2x3 arrays
b = np.random.random((5,2,3))
print(b)

[[[0.63330077 0.92580328 0.00753988]
  [0.4409438  0.63518793 0.77912173]]

 [[0.88581934 0.10006362 0.0324896 ]
  [0.55541426 0.07100823 0.79593735]]

 [[0.08037573 0.68161938 0.37635631]
  [0.29455155 0.06161955 0.52786795]]

 [[0.36276473 0.95190927 0.47750752]
  [0.89522802 0.97948055 0.34548974]]

 [[0.94164234 0.97661775 0.7788494 ]
  [0.53837827 0.31933458 0.82145607]]]


In [4]:
# How to generate 2 groups of 3 4x5 arrays
c = np.random.random((2,3,4,5))
print(c)

[[[[0.01953181 0.53737874 0.41611496 0.75906988 0.26393361]
   [0.99858546 0.10896473 0.16873527 0.60810849 0.57446606]
   [0.9338335  0.69377766 0.5599657  0.04491776 0.71591877]
   [0.97632581 0.6132979  0.95038163 0.73819476 0.54106711]]

  [[0.83052754 0.98533116 0.99663273 0.07170061 0.91994691]
   [0.33917937 0.77338304 0.78176128 0.68539076 0.60128109]
   [0.87628801 0.8895402  0.79955511 0.31741024 0.64396095]
   [0.62475972 0.75019225 0.18776619 0.2405271  0.54318714]]

  [[0.30803325 0.09050286 0.77538293 0.01343452 0.17961799]
   [0.11538295 0.83744874 0.10918054 0.44658542 0.51518967]
   [0.51216382 0.49732183 0.88273439 0.56320614 0.52901141]
   [0.98529779 0.82820168 0.64119549 0.43465706 0.56697091]]]


 [[[0.7296989  0.84867697 0.59431097 0.06608557 0.87785399]
   [0.92638738 0.35709963 0.7648952  0.55351697 0.27753224]
   [0.31957628 0.21999917 0.74980481 0.25034406 0.68860037]
   [0.86030967 0.61512254 0.97335134 0.36277151 0.29424221]]

  [[0.65479794 0.68160478 0.05

In [5]:
# Extrating data from arrays
import numpy as np
a = np.random.random((10,4))
print(a)

# First row of matrix a
print("")
print(a[0])

# First column of matrix a
print("")
print(a[:,0])

# Value in the fifth row and third column of matrix a
print("")
print(a[4,2])

[[0.3728587  0.79105821 0.58400004 0.50115836]
 [0.45460143 0.38248892 0.81357637 0.04661235]
 [0.43132768 0.20049226 0.7993785  0.6125389 ]
 [0.2968592  0.28264615 0.81939821 0.48166235]
 [0.73345519 0.32756946 0.06713244 0.1682817 ]
 [0.5901451  0.50538948 0.40543479 0.0696073 ]
 [0.77231239 0.77575603 0.40255715 0.58183723]
 [0.39301467 0.39828265 0.91455405 0.04523654]
 [0.25788859 0.80374857 0.30744698 0.18712105]
 [0.79609502 0.27976239 0.393336   0.9791386 ]]

[0.3728587  0.79105821 0.58400004 0.50115836]

[0.3728587  0.45460143 0.43132768 0.2968592  0.73345519 0.5901451
 0.77231239 0.39301467 0.25788859 0.79609502]

0.06713244262587559


In [6]:
# First group of array c
print("First group of array c\n",c[0],"\n")
# Second subgroup of the first group
print("Second subgroup of the first group: \n", c[0,1],"\n")
# Third row of the second subgroup
print("Third row of the second subgroup \n", c[0,1,2],"\n")
# Fourth column of the second subgroup
print("Fourth column of the second subgroup\n", c[0,1,:,3],"\n")
# Value in the third row and fourth column of the second subgroup
print("Value in the third row and fourth column of the second subgroup\n", c[0,1,2,3])

First group of array c
 [[[0.01953181 0.53737874 0.41611496 0.75906988 0.26393361]
  [0.99858546 0.10896473 0.16873527 0.60810849 0.57446606]
  [0.9338335  0.69377766 0.5599657  0.04491776 0.71591877]
  [0.97632581 0.6132979  0.95038163 0.73819476 0.54106711]]

 [[0.83052754 0.98533116 0.99663273 0.07170061 0.91994691]
  [0.33917937 0.77338304 0.78176128 0.68539076 0.60128109]
  [0.87628801 0.8895402  0.79955511 0.31741024 0.64396095]
  [0.62475972 0.75019225 0.18776619 0.2405271  0.54318714]]

 [[0.30803325 0.09050286 0.77538293 0.01343452 0.17961799]
  [0.11538295 0.83744874 0.10918054 0.44658542 0.51518967]
  [0.51216382 0.49732183 0.88273439 0.56320614 0.52901141]
  [0.98529779 0.82820168 0.64119549 0.43465706 0.56697091]]] 

Second subgroup of the first group: 
 [[0.83052754 0.98533116 0.99663273 0.07170061 0.91994691]
 [0.33917937 0.77338304 0.78176128 0.68539076 0.60128109]
 [0.87628801 0.8895402  0.79955511 0.31741024 0.64396095]
 [0.62475972 0.75019225 0.18776619 0.2405271  0.

In [7]:
# How to convert to an numpy array
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Sum of all elements in matrix a
print(np.sum(a))

19.02576101388321


In [9]:
# Sum of each column in matrix a
print(np.sum(a, axis=0))

[5.09855797 4.74719411 5.50681455 3.67319439]


In [10]:
# Sum of each row in matrix a
print(np.sum(a, axis=1))

[2.24907532 1.69727908 2.04373735 1.88056591 1.29643879 1.57057667
 2.5324628  1.75108791 1.55620519 2.44833201]


In [11]:
# Sum of all the elements in the first two groups of array b
np.sum(b[:2])

5.86262978695705

In [12]:
# Mean of all elements in matrix a
print(np.mean(a))

0.4756440253470802


In [13]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))

[0.5098558  0.47471941 0.55068145 0.36731944]


In [14]:
# Mean of each row in matrix a
print(np.mean(a, axis=1))

[0.56226883 0.42431977 0.51093434 0.47014148 0.3241097  0.39264417
 0.6331157  0.43777198 0.3890513  0.612083  ]


In [15]:
# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

0.48855248224642084

In [16]:
# How to select 2 of the subarrays in c
x = c[0,0]
print(x)
y = c[0,1]
print(y)

[[0.01953181 0.53737874 0.41611496 0.75906988 0.26393361]
 [0.99858546 0.10896473 0.16873527 0.60810849 0.57446606]
 [0.9338335  0.69377766 0.5599657  0.04491776 0.71591877]
 [0.97632581 0.6132979  0.95038163 0.73819476 0.54106711]]
[[0.83052754 0.98533116 0.99663273 0.07170061 0.91994691]
 [0.33917937 0.77338304 0.78176128 0.68539076 0.60128109]
 [0.87628801 0.8895402  0.79955511 0.31741024 0.64396095]
 [0.62475972 0.75019225 0.18776619 0.2405271  0.54318714]]


In [17]:
# Add elements of x and y together
print(np.add(x, y))

[[0.85005935 1.5227099  1.41274769 0.83077049 1.18388052]
 [1.33776483 0.88234776 0.95049655 1.29349925 1.17574715]
 [1.81012151 1.58331787 1.35952082 0.36232801 1.35987972]
 [1.60108552 1.36349015 1.13814782 0.97872186 1.08425425]]


In [18]:
# Subtract elements of x from elements of y
print(np.subtract(y, x))

[[ 0.81099574  0.44795242  0.58051777 -0.68736927  0.6560133 ]
 [-0.65940609  0.66441831  0.61302601  0.07728227  0.02681504]
 [-0.05754548  0.19576254  0.23958941  0.27249248 -0.07195783]
 [-0.35156609  0.13689435 -0.76261544 -0.49766766  0.00212003]]


In [19]:
# Multiply elements of x and y together
print(np.multiply(x, y))

[[0.0162217  0.52949602 0.41471379 0.05442578 0.24280491]
 [0.33869959 0.08427147 0.1319107  0.41679194 0.34541558]
 [0.8183071  0.61714312 0.44772344 0.01425736 0.46102373]
 [0.60996904 0.46009133 0.17844954 0.17755584 0.2939007 ]]


In [20]:
# Divide elements of y by elements of x
print(np.divide(y, x))

[[42.52179957  1.83358792  2.39508987  0.09445851  3.48552395]
 [ 0.33965983  7.09755397  4.6330639   1.12708631  1.04667819]
 [ 0.93837715  1.28216899  1.42786444  7.0664749   0.89948884]
 [ 0.63990905  1.2232102   0.19756926  0.32583149  1.00391824]]
